apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-server-poc
spec:
  version: 8.3.2
  count: 1
  elasticsearchRef:
    name: elasticsearch-poc
  kibanaRef:
    name: kibana-poc
  podTemplate:
    spec:
      containers:
      - name: apm-server
        resources:
          requests:
            memory: 2Gi
            cpu: 0.5
          limits:
            memory: 2Gi
            cpu: 2
  config:
    apm-server:
      jaeger.grpc.enabled: true
      jaeger.http.enabled: true
      rum.enabled: true
      rum.event_rate.limit: 300
      rum.event_rate.lru_size: 1000
      rum.allow_origins: ['']
      rum.library_pattern: "node_modules|bower_components|~"
      rum.exclude_from_grouping: "^/webpack"
      rum.source_mapping.enabled: true
      rum.source_mapping.cache.expiration: 5m
      rum.source_mapping.index_pattern: "apm--sourcemap*"
    output:
      elasticsearch:
        headers:
          X-My-Header: Just an example of a custom settings
