apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-server-poc
spec:
  version: 8.3.2
  count: 1
  elasticsearchRef:
    name: elasticsearch-poc
  kibanaRef:
    name: kibana-poc
  podTemplate:
    spec:
      containers:
      - name: apm-server
        resources:
          requests:
            memory: 2Gi
            cpu: 0.5
          limits:
            memory: 2Gi
            cpu: 2
  config:
    output:
      elasticsearch:
        headers:
          X-My-Header: Just an example of a custom settings
