apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-server-poc
spec:
  version: 8.3.1
  count: 1
  elasticsearchRef:
    name: elasticsearch-poc
  kibanaRef:
    name: kibana-poc
