apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elk-poc
spec:
  version: 8.3.1
  nodeSets:
  - name: default
    count: 3
    config:
      node.store.allow_mmap: false
