---
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: fleet-server-custom
spec:
  version: {{ .Values.version }}
  kibanaRef:
    name: kibana
  elasticsearchRefs:
  - name: elasticsearch
  mode: fleet
  fleetServerEnabled: true
  deployment:
    replicas: 1
    podTemplate:
      spec:
        serviceAccountName: fleet-server-custom
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0
#  http:
#    service:
#      spec:
#        type: ClusterIP
#    tls:
#      selfSignedCertificate:
#        disabled: true


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fleet-server-custom
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fleet-server-custom
rules:
- apiGroups: [""]
  resources:
  - pods
  - namespaces
  - nodes
  verbs:
  - get
  - watch
  - list
- apiGroups: ["coordination.k8s.io"]
  resources:
  - leases
  verbs:
  - get
  - create
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fleet-server-custom
subjects:
- kind: ServiceAccount
  name: fleet-server-custom
  namespace: {{ .Release.namespace }}
roleRef:
  kind: ClusterRole
  name: fleet-server-custom
  apiGroup: rbac.authorization.k8s.io

