apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: {{ .Values.version }}
  count: {{ .Values.kibana.replicas }}
  elasticsearchRef:
    name: elasticsearch
  http:
    service:
        spec:
            type: ClusterIP
    tls:
      selfSignedCertificate:
        subjectAltNames:
        - dns: kibana-kb-http.{{ .Values.namespace }}.svc.cluster.local
  podTemplate:
    spec:
      containers:
      - name: kibana
        env:
          - name: NODE_OPTIONS
            value: "--max-old-space-size=2048"
        resources:
          requests:
            memory: 2Gi
            cpu: 2
          limits:
            memory: 2Gi
            cpu: 2
  config:
    server.publicBaseUrl: https://{{ .Values.kibana.base_url }}
    xpack.fleet.registryProxyUrl: http://proxy.unicc.org:80
    xpack.fleet.agents.elasticsearch.hosts: ["https://elasticsearch-es-http.{{ .Values.namespace }}.svc:9200"]
    xpack.fleet.agents.fleet_server.hosts: ["https://fleet-server-custom-agent-http.{{ .Values.namespace }}.svc:8220"]
    xpack.fleet.packages:
    - name: system
      version: latest
    - name: elastic_agent
      version: latest
    - name: fleet_server
      version: latest
    - name: kubernetes
      version: 1.21.1
    - name: apm
      version: latest
    - name: log
      version: latest
    xpack.fleet.agentPolicies:
      - name: Fleet Server on ECK policy
        id: eck-fleet-server
        is_default_fleet_server: true
        namespace: default
        monitoring_enabled:
          - logs
          - metrics
        package_policies:
        - name: fleet_server-1
          id: fleet_server-1
          package:
            name: fleet_server
      - name: Elastic LOGS Agent on ECK policy
        id: eck-agent-logs
        namespace: default
        monitoring_enabled:
        - logs
        - metrics
        unenroll_timeout: 900
        is_default: true
        package_policies:
        - name: elastic_agent-1
          id: elastic_agent-1
          package:
            name: elastic_agent
        - name: system-1
          id: system-1
          package:
            name: system
          inputs:
            - type: system/metrics
              enabled: true
              vars:
                - name: system.hostfs
                  value: /hostfs
              streams:
                - data_stream:
                    dataset: system.core
                  enabled: true
                  vars:
                    - name: period
                      value: 20s
            - type: winlog
              enabled: false
        - package:
            name: log
          name: log-1
          inputs:
          - type: logfile
            enabled: true
            streams:
            - data_stream:
                dataset: log.log
              enabled: true
              vars:
              - name: paths
                value:
                - '/var/lib/docker/containers/*/*.log'
#                - '/var/log/containers/*.log'
#        - package:
#            name: apm
#          name: apm-1
#          inputs:
#          - type: apm
#            enabled: true
#            vars:
#            - name: host
#              value: 0.0.0.0:8200
#            - name: url
#              value: http://apm.{{ .Values.namespace }}.svc.cluster.local:8200

#      - name: Elastic APM Agent on ECK policy
#        id: eck-agent-apm
#        namespace: default
#        monitoring_enabled:
#        - logs
#        - metrics
#        unenroll_timeout: 900
#        is_default: true
#        package_policies:
#        - package:
#            name: system
#          name: system-1
##        - package:
##            name: kubernetes
##          name: kubernetes-1
#        - package:
#            name: apm
#          name: apm-1
#          inputs:
#          - type: apm
#            enabled: true
#            vars:
#            - name: host
#              value: 0.0.0.0:8200
#            - name: url
#              value: http://apm.{{ .Values.namespace }}.svc.cluster.local:8200
