apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-poc
spec:
  version: 8.3.2
  count: 2
  elasticsearchRef:
    name: elasticsearch-poc
  http:
    service:
        spec:
            type: ClusterIP
  podTemplate:
    spec:
      containers:
      - name: kibana
        env:
          - name: NODE_OPTIONS
            value: "--max-old-space-size=2048"
          - name: HTTP_PROXY
            value: "http://proxy.unicc.org:80"
          - name: HTTPS_PROXY
            value: "http://proxy.unicc.org:80"
          - name: NO_PROXY
            value: "localhost,127.0.0.1,172.17.0.0/16,10.0.0.0/8,.unicc.org"
        resources:
          requests:
            memory: 2Gi
            cpu: 2
          limits:
            memory: 2Gi
            cpu: 2
  config:
    server.publicBaseUrl: https://{{ .Values.kibana_base_url }}
    xpack.fleet.agents.elasticsearch.hosts: ["https://elasticsearch-poc-es-http.default.svc:9200"]
    xpack.fleet.agents.fleet_server.hosts: ["https://fleet-server-poc-agent-http.default.svc:8220"]
    xpack.fleet.packages:
    - name: system
      version: latest
    - name: elastic_agent
      version: latest
    - name: fleet_server
      version: latest
    - name: apm
      version: latest
    xpack.fleet.agentPolicies:
    - name: Fleet Server on ECK policy
      id: eck-fleet-server
      is_default_fleet_server: true
      namespace: default
      monitoring_enabled:
      - logs
      - metrics
      package_policies:
      - name: fleet_server-1
        id: fleet_server-1
        package:
          name: fleet_server
    - name: Elastic Agent on ECK policy
      id: eck-agent
      namespace: default
      monitoring_enabled:
      - logs
      - metrics
      unenroll_timeout: 900
      is_default: true
      package_policies:
      - name: system-1
        id: system-1
        package:
          name: system
      - package:
          name: apm
        name: apm-1
        inputs:
        - type: apm
          enabled: true
          vars:
          - name: host
            value: 0.0.0.0:8200
