apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-poc
spec:
  version: 8.3.1
  count: 2
  elasticsearchRef:
    name: elasticsearch-poc
  http:
    service:
      spec:
        type: LoadBalancer # default is ClusterIP
    tls:
      selfSignedCertificate:
        subjectAltNames:
        - ip: 1.2.3.4
        - dns: kibana.rancher-poc.unicc.org
