apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-poc
spec:
  version: 8.3.2
  count: 2
  elasticsearchRef:
    name: elasticsearch-poc
  http:
    service:
        spec:
            type: ClusterIP
  podTemplate:
    spec:
      containers:
      - name: kibana
        env:
          - name: NODE_OPTIONS
            value: "--max-old-space-size=2048"
#          - name: HTTP_PROXY
#            value: "http://proxy.unicc.org:80"
#          - name: HTTPS_PROXY
#            value: "http://proxy.unicc.org:80"
#          - name: NO_PROXY
#            value: "localhost,127.0.0.1,172.17.0.0/16,10.0.0.0/8,.unicc.org,.svc"
        resources:
          requests:
            memory: 2Gi
            cpu: 2
          limits:
            memory: 2Gi
            cpu: 2
  config:
    server.publicBaseUrl: https://{{ .Values.kibana_base_url }}
    xpack.fleet.registryProxyUrl: http://proxy.unicc.org:80
    xpack.fleet.agents.elasticsearch.hosts: ["https://elasticsearch-poc-es-http.monitoring-tools-poc.svc:9200"]
    xpack.fleet.agents.fleet_server.hosts: ["https://fleet-server-poc-agent-http.monitoring-tools-poc.svc:8220"]
    xpack.fleet.packages:
    - name: system
      version: latest
    - name: elastic_agent
      version: latest
    - name: fleet_server
      version: latest
    - name: kubernetes
      # pinning this version as the next one introduced a kube-proxy host setting default that breaks this recipe,
      # see https://github.com/elastic/integrations/pull/1565 for more details
      version: 1.21.1
    - name: apm
      version: latest
    - name: log
      version: latest
    xpack.fleet.agentPolicies:
    - name: Fleet Server on ECK policy
      id: eck-fleet-server
      is_default_fleet_server: true
      namespace: default
      monitoring_enabled:
      - logs
      - metrics
      package_policies:
      - name: fleet_server-1
        id: fleet_server-1
        package:
          name: fleet_server
    - name: Elastic K8s Agent on ECK policy
      id: eck-agent-k8s
      namespace: default
      monitoring_enabled:
      - logs
      - metrics
      unenroll_timeout: 900
      is_default: true
      package_policies:
      - package:
          name: system
        name: system-1
      - package:
          name: kubernetes
        name: kubernetes-1
    - name: Elastic APM Agent on ECK policy
      id: eck-agent-apm
      namespace: default
      monitoring_enabled:
      - logs
      - metrics
      unenroll_timeout: 900
      is_default: true
      package_policies:
      - name: system-1
        id: system-1
        package:
          name: system
      - package:
          name: apm
        name: apm-1
        inputs:
        - type: apm
          enabled: true
          vars:
          - name: host
            value: 0.0.0.0:8200
    - name: Elastic Logs Agent on ECK policy
      id: eck-agent
      namespace: default
      monitoring_enabled:
      - logs
      - metrics
      unenroll_timeout: 900
      is_default: true
      package_policies:
      - name: system-1
        id: system-1
        package:
          name: system
      - package:
          name: log
        name: log-1
        inputs:
        - type: logfile
          enabled: true
          streams:
          - data_stream:
              dataset: log.log
            enabled: true
            vars:
            - name: paths
              value:
              - '/var/log/containers/*${kubernetes.container.id}.log'
            - name: custom
              value: |
                symlinks: true
                condition: ${kubernetes.namespace} == 'default'
