apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  name: kibana-poc-ingress
spec:
  rules:
  - host: {{ .Values.kibana_base_url }}
    http:
      paths:
      - backend:
          service:
            name: kibana-poc-kb-http
            port:
              number: 5601
        path: /
        pathType: ImplementationSpecific
