apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-poc
spec:
  version: 8.3.1
  count: 2
  elasticsearchRef:
    name: elasticsearch-poc
  http:
    service:
        spec:
            type: LoadBalancer
