
kibana:
  base_url: kibana.rancher-poc.unicc.org
  replicas: 1

elasticsearch:
  master:
    replicas: 3
    persistence:
      storageClassName: longhorn
      size: 5Gi

  data:
    replicas: 2
    persistence:
      storageClassName: longhorn
      size: 10Gi

