
version: 8.3.2
namespace: elk-stack
kibana:
  base_url: kibana-fleet.rancher-poc.unicc.org
  replicas: 1



elasticsearch:
  base_url: elasticsearch-fleet.rancher-poc.unicc.org
  master:
    replicas: 1
    persistence:
      storageClassName: longhorn
      size: 2Gi

  data:
    replicas: 1
    persistence:
      storageClassName: longhorn
      size: 5Gi

