
version: 8.3.2
namespace: elk-stack

petclinic:
  nodeport: 30002
kibana:
  base_url1: kibana-fleet.rancher-poc.unicc.org
  base_url2: kibana.rancher-poc.unicc.org
  replicas: 1



elasticsearch:
  base_url1: elasticsearch-fleet.rancher-poc.unicc.org
  base_url2: elasticsearch.rancher-poc.unicc.org
  master:
    replicas: 1
    persistence:
      storageClassName: longhorn
      size: 2Gi

  data:
    replicas: 2
    persistence:
      storageClassName: longhorn
      size: 5Gi

