
version: 8.3.2
namespace: elk-stack
base_url: rancher-poc.unicc.org

petclinic:
  nodeport: 30002
kibana:
  replicas: 1



elasticsearch:
  master:
    replicas: 1
    persistence:
      storageClassName: longhorn
      size: 5Gi

  data:
    replicas: 2
    persistence:
      storageClassName: longhorn
      size: 30Gi

