
version: 8.3.2
namespace: elk-stack

petclinic:
  nodeport: 30002
kibana:
  base_url: kibana-{{ .Release.namespace }}.rancher-poc.unicc.org
  replicas: 1



elasticsearch:
  base_url1: elasticsearch-{{ .Release.namespace }}.rancher-poc.unicc.org
  master:
    replicas: 1
    persistence:
      storageClassName: longhorn
      size: 5Gi

  data:
    replicas: 2
    persistence:
      storageClassName: longhorn
      size: 30Gi

